[package]
name = "advent-of-code-24"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.13.0"
memoize = "0.4.2"
ndarray-linalg = "0.16.0"
regex = "1.11.1"

[dependencies.ndarray]
version = "0.15.2"
features = ["blas", "approx", "std"]
default-features = false
